server:
  port: 8002
#  servlet:
#    context-path: /content-service
rocketmq:
  name-server: 49.234.46.251:9876
  producer:
    # 必须指定 group
    group: test-group
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    generator:
      write-numbers-as-strings: true
minio:
  endPoint: http://49.234.46.251:9000
  accessKey: admin
  secretKey: admin123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.om1ga.share.content.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn