server:
  port: 8002
  servlet:
    context-path: /content-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    top.om1ga.share.content.mapper: debug