server:
  port: 8002
#  servlet:
#    context-path: /content-service
rocketmq:
  name-server: 49.234.46.251:9876
  producer:
    # 必须指定 group
    group: test-group
spring:
  jackson:
    generator:
      write-numbers-as-strings: true