GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTY2NzA3OTYsInBob25lIjoiMTM5NTE5MDUxNzEiLCJpZCI6MSwiZXhwIjoxNjk2NjcwODk2LCJpYXQiOjE2OTY2NzA3OTZ9.OJOu4fyeQGAFx1UNu2faBZCM2TQ7O-NEMLf5PuxHUG0

###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone":"13951905171",
  "password":"123123"
}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "password":"1231233"
}
###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone":"18601461563",
  "password":"888888"
}
###