GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone":"13951905171",
  "password":"123123"
}

> {%
      client.global.set("token",response.body.data.token);
 %}
###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "password":"1231233"
}
###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone":"18601461563",
  "password":"888888"
}
###
GET http://localhost:8000/content-service/share/notice
Accept: application/json
###
GET http://localhost:8000/content-service/share/list?title=并发编程
Accept: application/json
###
GET http://localhost:8000/content-service/share/list?pageNo=3&pageSize=2
Accept: application/json
token: {{token}}
###
GET http://localhost:8000/user-service/user/2
Accept: application/json
token: {{token}}
###
GET http://10.20.236.110:8000/content-service/share/1
Accept: application/json
token: {{token}}
###
PUT http://localhost:8000/user-service/user/update-bonus
Content-Type: application/json
token: {{token}}

{
  "userId": 1,
  "bonus": -11
}
###
POST http://localhost:8000/content-service/share/exchange
Content-Type: application/json
token: {{token}}

{
  "userId": 1,
  "shareId": 11
}
###
POST http://localhost:8000/content-service/share/contribute
Content-Type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 1,
  "author": "尤雨溪",
  "title": "详解 Vue.js",
  "isOriginal": 1,
  "price": 20,
  "downloadUrl": "https://cn.vuejs.org/",
  "cover": "https://niit-soft.oss-cn-hangzhou.aliyuncs.com/share-app/Vue.jpg",
  "summary": "详解 Vue.js详解 Vue.js详解 Vue.js详解 Vue.js详解 Vue.js"
}
###
GET http://localhost:8000/content-service/share/my-contribute
Accept: application/json
token: {{token}}