server:
  port: 8001
#  servlet:
#    context-path: /user-service
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
rocketmq:
  name-server: 49.234.46.251:9876
  consumer:
    group: test-group
logging:
  level:
    top.om1ga.share.user.mapper: debug